/**
 * scripts/extract-docx.ts — DOCX text extractor (mammoth-based).
 *
 * Build-time tool for surfacing text from .docx sources for the calibration items
 * pending OCR (per Phase A.9 / Phase H.1). Wires DOCX into the same source-anchor
 * pattern as scripts/extract-mcfirst.ts uses for PDFs.
 *
 * Usage:
 *   npm run extract:docx -- "<absolute path to .docx>"
 *
 * Outputs:
 *   src/data/<basename>.extracted.json   { source_path, source_hash, text, paragraphs[] }
 *
 * Idempotent — skips re-extraction unless source hash differs (or `--force`).
 *
 * Per architecture-plan §4 + JOSHUA DIRECTIVE Rec #2 scope split:
 *   This extractor doesn't author content. It only fills `stimulus_pending_ocr` slots.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve, basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as mammoth from 'mammoth';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DATA_DIR = resolve(ROOT, 'src/data');

const argv = process.argv.slice(2);
const FORCE = argv.includes('--force');
const inputs = argv.filter((a) => !a.startsWith('--'));

if (inputs.length === 0) {
  console.error('Usage: npm run extract:docx -- "<absolute .docx path>" [more paths...]');
  process.exit(1);
}

mkdirSync(DATA_DIR, { recursive: true });

async function extractOne(path: string): Promise<void> {
  if (!existsSync(path)) {
    console.error(`[extract-docx] missing: ${path}`);
    process.exit(1);
  }
  const bytes = readFileSync(path);
  const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 16);
  const outName = basename(path).replace(/\.docx$/i, '').replace(/[^a-zA-Z0-9._-]+/g, '-') + '.extracted.json';
  const outPath = join(DATA_DIR, outName);

  if (!FORCE && existsSync(outPath)) {
    try {
      const prev = JSON.parse(readFileSync(outPath, 'utf-8'));
      if (prev.source_hash === hash) {
        console.log(`[extract-docx] cache hit: ${outName}`);
        return;
      }
    } catch {
      /* fall through */
    }
  }

  const result = await mammoth.extractRawText({ buffer: bytes });
  const text = result.value;
  const paragraphs = text
    .split(/\n+/)
    .map((p) => p.trim())
    .filter(Boolean);

  const out = {
    $comment: 'Generated by scripts/extract-docx.ts (mammoth raw text). Do not hand-edit.',
    extracted_at: new Date().toISOString(),
    extractor: 'mammoth (raw text)',
    source_path: path,
    source_hash: hash,
    paragraph_count: paragraphs.length,
    text,
    paragraphs,
    messages: result.messages.map((m) => ({ type: m.type, message: m.message })),
  };
  writeFileSync(outPath, JSON.stringify(out, null, 2));
  console.log(
    `[extract-docx] wrote ${outName} (${paragraphs.length} paragraphs, ${(text.length / 1024).toFixed(1)} KB)`,
  );
}

(async () => {
  for (const p of inputs) {
    try {
      await extractOne(p);
    } catch (e) {
      console.error(`[extract-docx] failed on ${p}:`, e);
      process.exit(1);
    }
  }
})();
