import { StemDrill, RoleQuestion } from './types';

export const MODULE_1_INTRO = 'The ability to de-abstractify \u2014 translating vague and abstract terms that appear in answer choices into their stimulus equivalents \u2014 and knowing exactly what they are referring to is one of the most important skills that the advanced student needs to master. If you do not have this ability, often you will end up choosing a wrong answer choice even if you knew what you were looking for. You simply did not understand what the answer choice was trying to say. In other words, advanced students can read through a list of abstract answer choices and know exactly what they are referring to.';

export const MODULE_2_INTRO = 'Take a look at the following questions. Try to go through the questions practicing the skills developed earlier in the chapter. Try to follow the steps as outlined, paying special attention to the answer choices! Do the questions first before looking at the explanations!\n\nAgain, if you find yourself struggling with some of the questions, don\'t worry too much about timing. Use the opportunity to develop a systematic approach to these types of questions, fill in knowledge gaps, and familiarize yourself with how to decipher an abstract answer choice. For the advanced test taker, try to aim for under 3 minutes per question, 2 minutes per question is really good, granted that you are getting them correct and following the steps.\n\nStructurally analyzing the stimulus is the first step to successfully tackling Role questions. In fact, complicated arguments with multiple premises, intermediate conclusions, and background information is the most common characteristic of harder Role questions.';

export const stemDrills: StemDrill[] = [
  {
    id: 1,
    rawStem: 'It is used to illustrate the general principle that the argument presupposes',
    keywords: [
      { word: 'illustrate', definition: 'Provide an example of' },
      { word: 'general principle', definition: 'A rule on what we should/shouldn\'t do that applies to multiple conditions and scenarios. For example, "John should go to bed earlier" is NOT a principle (just about one person). "Those who are tired in the morning should strive to get to bed earlier" IS a principle \u2014 it applies to a category of people.' },
      { word: 'presuppose', definition: 'Require (a necessary condition). On the LSAT, "presuppose" simply means "require."' },
    ],
    coachTranslation: 'The statement is an example. Behind this example is a principle (a broad rule). And this principle is required in order for the author to advance their argument. Three requirements must be met: (1) the statement in question must be an example, (2) behind this example is a principle on what we should or shouldn\'t do, and (3) this principle is required in order for the author to advance their argument.',
    concreteExample: 'Despite a high paying job, John was extremely stressed out and depressed, so there are intangible things in life that we must pursue to find true happiness.\n\nJohn\'s situation is the illustration of a general principle; namely that having a lot of money isn\'t enough to make you happy. Is this principle required in order for the conclusion to stand? Yes, the conclusion says factors other than money must be considered in order to be happy. The underlined statement satisfies all three requirements and if this was a Role question, this would be the correct answer.',
    requirements: [
      'The statement in question must be an example',
      'Behind this example is a principle on what we should or shouldn\'t do',
      'This principle is required in order for the author to advance their argument',
    ],
  },
  {
    id: 2,
    rawStem: 'It is an illustration of a premise that is used to support the argument\'s conclusion',
    keywords: [
      { word: 'illustration', definition: 'An example' },
      { word: 'premise', definition: 'A supporting statement/evidence' },
    ],
    coachTranslation: 'The statement is an example in the stimulus. Furthermore, it is an illustration of a premise. So when examining this answer choice, we must isolate the premise/premises that appear in the argument and ask ourselves, is the quoted statement an example of what the premise is trying to say?',
    concreteExample: 'John has been smoking two packs a day since he was sixteen, last week he was diagnosed with lung cancer. Smoking is a direct cause of lung cancer. We must avoid cigarettes at all costs if we want to stay healthy.\n\nWhat is the premise here? Smoking causes lung cancer. What is the conclusion? Don\'t smoke. John\'s case is an illustration of the causal relationship between smoking and lung cancer. Requirement satisfied.',
  },
  {
    id: 3,
    rawStem: 'It is used to counter a consideration that might be taken to undermine the argument\'s conclusion',
    keywords: [
      { word: 'counter', definition: 'Argue against / shut down' },
      { word: 'consideration', definition: 'A point or objection \u2014 referring to a real or potential counter argument. A counter argument runs contrary to the author\'s conclusion.' },
      { word: 'undermine', definition: 'Weaken or attack' },
    ],
    coachTranslation: 'There is a real or potential counter-argument that runs contrary to the author\'s conclusion. The quoted statement is a pre-emptive strike \u2014 the author anticipates the objection and shuts it down in advance. If I say "going to college is a great way to enjoy a higher standard of living," but you respond with "but many college graduates have to take years to pay back debt," you are making a counter argument. If I had anticipated your potential objection, I can shut you down in advance. That\'s what is meant by "countering a consideration that might be taken to undermine the argument\'s conclusion."',
    concreteExample: 'College graduates make more money than they would if they didn\'t go to college, even if they are paying off student loans plus interest. So going to college is a great way to make more money and enjoy a better life.\n\nHere, the underlined statement is both a premise as well as a pre-emptive strike against a potential objection, namely that graduates end up with so much debt that going to college doesn\'t make sense.',
  },
  {
    id: 4,
    rawStem: 'It makes an observation that, according to the argument, is insufficient to justify the claim that the argument concludes is false',
    keywords: [
      { word: 'observation', definition: 'A factual statement / piece of evidence' },
      { word: 'insufficient', definition: 'Not enough to prove' },
      { word: 'concludes is false', definition: 'The author is arguing AGAINST a claim \u2014 someone has made a claim, and the author is saying that claim is false' },
    ],
    coachTranslation: 'A key piece of information: there is a claim that the argument concludes is false. The author is arguing AGAINST a claim. So we have two viewpoints. The opponent made an observation in support of their view, but the author says that observation is not enough to prove anything, and subsequently goes on to argue that the opponent\'s claim is false.',
    concreteExample: 'John: Celebrities have the biggest smiles in front of the camera, so they must be the happiest people alive.\n\nDavid: That is not true. Many celebrities suffer from depression and substance abuse. Smiling in front of the camera doesn\'t mean a thing, they could simply be putting on a show for the audience.\n\nDoes the underlined statement fit? Yes. David is arguing that John\'s claim is false. David also suggests that the observation John makes in support of his claim is insufficient to justify his claim.',
    requirements: [
      'There must be an opposing view',
      'The author must be arguing against this opposing view and declaring it false',
      'The opponent must have provided an observation as a basis of support for their view',
      'The author must have made the claim that this observation is not enough to demonstrate the truth of the opponent\'s view',
    ],
  },
  {
    id: 5,
    rawStem: 'It describes a phenomenon for which the argument\'s conclusion is offered as an explanation',
    keywords: [
      { word: 'phenomenon', definition: 'An observed event or fact' },
      { word: 'explanation', definition: 'On the LSAT, the word "explanation" has a very strict and precise meaning: it simply means "cause." Whenever you see the word "explanation" in an answer choice, check the stimulus for cause-effect reasoning. If it\'s not there, then this answer would be wrong.' },
    ],
    coachTranslation: 'This answer choice is referring to something where there is a cause and effect relationship in the argument, but instead of the cause being the premise and the effect being the conclusion, the order is reversed. The author describes a phenomenon and concludes what caused it. See PT43-S3-Q23 in the Find the Conclusion chapter if you had forgotten.',
    concreteExample: 'Smoking is a leading cause of lung cancer. John has lung cancer, therefore he must surely have been a heavy smoker.\n\nJohn having lung cancer is the phenomenon. The author subsequently concludes that it must be smoking which caused his lung cancer. The cause-effect relationship goes like this: smoking \u2192 lung cancer, and the cause/explanation is in fact the conclusion in this example.',
    lsatNote: 'On the LSAT, "explanation" strictly means "cause." Whenever you see this word in an answer choice, immediately check the stimulus for cause-effect reasoning. If there is no cause-effect structure, this answer is wrong.',
  },
  {
    id: 6,
    rawStem: 'It is a general principle whose validity the argument questions',
    keywords: [
      { word: 'general principle', definition: 'A broad rule applying to multiple scenarios' },
      { word: 'validity', definition: 'Truth / correctness' },
      { word: 'questions', definition: 'Challenges / attacks' },
    ],
    coachTranslation: 'The quoted statement is a general principle, but it\'s a general principle that the argument is questioning/attacking. So if we are confronted with this answer choice, we must go back to the stimulus to make sure it satisfies two requirements: (1) the quoted statement is indeed a general principle, and (2) the author is arguing against the truth of this principle.',
    concreteExample: 'It has been said that the best way to approach any situation is to be yourself. But this cannot be true. What if you are a selfish, egotistical or horrible person? Surely we must strive to better ourselves and be the best we can be?',
    requirements: [
      'The quoted statement is indeed a general principle',
      'The author is arguing against the truth of this principle',
    ],
  },
  {
    id: 7,
    rawStem: 'It denies a claim that the argument takes to be assumed in the reasoning it rejects',
    keywords: [
      { word: 'denies', definition: 'Rejects / contradicts' },
      { word: 'assumed', definition: 'Taken for granted without proof' },
      { word: 'reasoning it rejects', definition: 'The opponent\'s argument' },
    ],
    coachTranslation: 'This one is very similar to stem #4. The argument is rejecting another person\'s reasoning. So the author is arguing against someone else. But are they rejecting that view outright? No, the author does something much more nuanced. The author thinks the reasoning used by their opponent has made an assumption, and instead of going after the opponent\'s argument, our author is going after the opponent\'s assumption.',
    concreteExample: 'John: I\'ve studied so hard for the finals, I\'m definitely going to ace the exam!\n\nDavid: Studying hard doesn\'t guarantee you will do well. The exams are graded on a curve, and everyone else has studied just as hard.',
    lsatNote: 'We will look at the nature of assumptions in a subsequent chapter, as well as in Sufficient and Necessary Assumption question types.',
  },
  {
    id: 8,
    rawStem: 'It is a claim for which no justification is provided but that is required to establish the argument\'s main conclusion',
    keywords: [
      { word: 'no justification', definition: 'No other statement supports it' },
      { word: 'required', definition: 'Necessary' },
      { word: 'establish', definition: 'Prove / make valid' },
    ],
    coachTranslation: 'There are two important pieces of information. First, it is "required" to establish the argument\'s main conclusion \u2014 that means it\'s necessary for the main conclusion to be valid. So it\'s therefore either a premise or an intermediate conclusion. Second, it\'s a claim for which no justification is provided. Remember the difference: premises support the conclusion but do not have any other statements supporting them, whereas intermediate conclusions both support the conclusion and are supported by premises. So when we have a statement which supports the conclusion but is not supported by others, it can only mean one thing: we are talking about a premise here. And if it were untrue, the conclusion would not stand.',
    concreteExample: 'I found an Olympic gold medal in the swim team locker room. It must have originally belonged to John. John is always losing things and he participated in the Olympics.\n\nJohn\'s participation in the Olympics is a requirement for the conclusion to stand. In order for John to be the original owner of the medal, he MUST have been a participant at least. John\'s participation in the Olympics is also a premise that supports the example argument\'s conclusion.',
  },
  {
    id: 9,
    rawStem: 'It is a claim for which justification is provided and that, if true, establishes the truth of the argument\'s main conclusion',
    keywords: [
      { word: 'justification is provided', definition: 'Another statement supports it' },
      { word: 'establishes the truth', definition: 'Guarantees the conclusion' },
    ],
    coachTranslation: 'Very similar to stem #8, but with two important caveats. This answer choice HAS justification provided, while supporting the main conclusion, so it\'s an intermediate conclusion. It also guarantees/establishes the truth of the conclusion.',
    concreteExample: 'All practicing lawyers must have passed the bar. John is a partner at a prestigious law firm and therefore he is a practicing lawyer, so he must have passed the bar.\n\nJohn being a practicing lawyer is supported by the fact that he is a partner at a law firm. This satisfies the intermediate conclusion requirement. Does John being a practicing lawyer establish the fact that he has passed the bar? Yes, it is mentioned in the first statement/premise that all practicing lawyers must have passed the bar.',
  },
  {
    id: 10,
    rawStem: 'It is what the author\'s argument purports to explain',
    keywords: [
      { word: 'purports to explain', definition: 'Claims to provide the cause for' },
    ],
    coachTranslation: 'This is identical to stem #5: the author describes an effect/result/phenomenon, and argues for a specific cause. "Explain" on the LSAT = "provide a cause for." So whenever you see the word "explain" or "explanation" in an answer choice, check the stimulus for cause-effect reasoning. If it\'s not there, then this answer would be wrong.',
    concreteExample: 'Smoking is a leading cause of lung cancer. John has lung cancer, therefore he must surely have been a heavy smoker.\n\nJohn having lung cancer is the phenomenon (the effect). The author\'s argument purports to explain it by concluding that John must have been a heavy smoker (the cause). The cause/explanation IS the conclusion.',
    lsatNote: 'Identical to stem #5 in structure. Whenever "explain" or "explanation" appears, it strictly means providing a cause. No cause-effect in the stimulus = wrong answer.',
  },
  {
    id: 11,
    rawStem: 'It is a hypothesis that the argument attempts to undermine by calling into question the sufficiency of the evidence',
    keywords: [
      { word: 'hypothesis', definition: 'A potential explanation / potential cause. In science, a hypothesis is offered by scientists to try to explain a phenomenon in the physical world or universe. On the LSAT, it can be understood as a "potential explanation/potential causation" and usually appears in science/medicine themed LR stimuli.' },
      { word: 'undermine', definition: 'Weaken / challenge' },
      { word: 'sufficiency of the evidence', definition: 'Whether the evidence is enough' },
    ],
    coachTranslation: 'What is a hypothesis? Why did different types of birds have physical features adapted to their environments? Darwin hypothesized that species can change over time, adapting via physical modifications generation after generation. Darwin came up with a hypothesis \u2014 The Theory of Evolution \u2014 that has been supported by evidence gathered by him and subsequent scientists. A hypothesis is simply a posited causal explanation of a phenomenon, explaining WHY something is the way it is.\n\nSo what is this answer choice saying? The argument is attempting to undermine this hypothesis. It does so by saying that the evidence out there is not enough to support such a hypothesis.',
    concreteExample: 'When we come to this answer choice, we must make sure: (1) there is a hypothesis present in the stimulus (the quoted statement being that hypothesis), (2) the author is challenging this hypothesis, and (3) the author does so by suggesting that the available evidence is not enough to support this hypothesis.\n\nFor example, if scientists hypothesize that a certain diet causes longevity, and the author argues that the studies cited have too small a sample size or too many confounding variables, that would match this stem.',
    requirements: [
      'There is a hypothesis present in the stimulus (the quoted statement is that hypothesis)',
      'The author is challenging this hypothesis',
      'The author does so by suggesting that the available evidence is not enough to support this hypothesis',
    ],
  },
  {
    id: 12,
    rawStem: 'It is the conclusion of the argument as a whole but is not the only explicitly stated conclusion in the argument',
    keywords: [
      { word: 'conclusion of the argument as a whole', definition: 'The MAIN conclusion' },
      { word: 'not the only explicitly stated conclusion', definition: 'There is also an intermediate conclusion' },
    ],
    coachTranslation: 'Two pieces of key information. The first is straightforward: we are talking about the main conclusion here. But note that it "is not the only explicitly stated conclusion in the argument." That can only mean one thing: we have an intermediate conclusion in the argument as well. So if confronted with this answer choice, make sure that (1) the statement we are talking about is in fact the main conclusion of the argument, and (2) the argument contains a separate intermediate conclusion.',
    concreteExample: 'The main conclusion is the overall point the author is trying to make. An intermediate conclusion is a statement that is both supported by premises AND supports the main conclusion. When this answer choice applies, you\'ll see an argument with at least three levels: premises supporting an intermediate conclusion, which in turn supports the main conclusion \u2014 making two explicitly stated conclusions in the argument.',
  },
  {
    id: 13,
    rawStem: 'It is a statement that the argument is intended to support but is not the conclusion of the argument as a whole',
    keywords: [
      { word: 'intended to support', definition: 'The argument provides evidence for it' },
      { word: 'not the conclusion of the argument as a whole', definition: 'Not the main conclusion' },
    ],
    coachTranslation: 'Something that is supported by the argument but is not the main conclusion \u2014 that\'s an intermediate conclusion we are talking about here. The key signal is "supported by the argument" + "not the main conclusion."',
    concreteExample: 'In any argument with an intermediate conclusion: the intermediate conclusion is supported by premises, but it also supports the main conclusion. Look for a statement that has evidence behind it yet is not the final point the author is making.',
  },
  {
    id: 14,
    rawStem: 'It is a statement for which some evidence is provided and that itself is offered as support for the conclusion of the argument as a whole',
    keywords: [
      { word: 'some evidence is provided', definition: 'Another statement supports it' },
      { word: 'offered as support for the conclusion', definition: 'It supports the main conclusion' },
    ],
    coachTranslation: 'Same as #13 \u2014 this is also describing an intermediate conclusion. The statement in question is supported by evidence/support (making it not just a bare premise), and it also supports the main conclusion. Classic intermediate conclusion structure: Premise \u2192 Intermediate Conclusion \u2192 Main Conclusion.',
    concreteExample: 'The statement is supported by a premise and in turn supports the main conclusion. For example: "All dogs are mammals [premise]. Rex is a dog, so Rex is a mammal [intermediate conclusion]. Therefore Rex is warm-blooded [main conclusion]." The intermediate conclusion has evidence (Rex is a dog) and supports the main conclusion.',
  },
  {
    id: 15,
    rawStem: 'It is the conclusion of the argument as a whole and is supported by another statement for which support is offered',
    keywords: [
      { word: 'conclusion of the argument as a whole', definition: 'The main conclusion' },
      { word: 'another statement for which support is offered', definition: 'An intermediate conclusion exists' },
    ],
    coachTranslation: 'Same as #12: the quoted statement is the main conclusion, and it is supported by an intermediate conclusion (a statement that itself has support). When faced with an answer choice like this, make sure it is indeed the main conclusion that the question is asking us to analyze, and make sure the argument contains an intermediate conclusion.',
    concreteExample: 'The main conclusion is supported by an intermediate conclusion, which is in turn supported by a premise. This is the full argument chain: Premise \u2192 Intermediate Conclusion \u2192 Main Conclusion. The main conclusion sits at the top of the chain, and the "another statement for which support is offered" is the intermediate conclusion below it.',
  },
];

export const roleQuestions: RoleQuestion[] = [
  {
    id: 'PT34-S3-Q14',
    stimulus: 'People\'s political behavior frequently does not match their rhetoric. Although many complain about government intervention in their lives, they tend not to re-elect inactive politicians. But a politician\'s activity consists largely in the passage of laws whose enforcement affects voters\' lives. Thus, voters often re-elect politicians whose behavior they resent.',
    questionStem: 'Which one of the following most accurately describes the role played in the argument by the claim that people tend not to re-elect inactive politicians?',
    options: [
      { letter: 'A', text: 'It describes a phenomenon for which the argument\'s conclusion is offered as an explanation' },
      { letter: 'B', text: 'It is a premise offered in support of the conclusion that voters often re-elect politicians whose behavior they resent' },
      { letter: 'C', text: 'It is offered as an example of how a politician\'s activity consists largely in the passage of laws whose enforcement interferes with voters\' lives' },
      { letter: 'D', text: 'It is a generalization based on the claim that people complain about government intervention in their lives' },
      { letter: 'E', text: 'It is cited as evidence that people\'s behavior never matches their political beliefs' },
    ],
    correctAnswer: 'B',
    difficultTrait: {
      number: 1,
      title: 'Categorize Each Statement',
      text: 'Make sure you are clearly categorizing each statement that appears in the stimulus and argument as you are reading it. Don\'t confuse the intermediate conclusion for the main conclusion.',
    },
    walkthrough: [
      'Statement 1: "People\'s political behavior frequently does not match their rhetoric" \u2014 This can be an opinion of the author or an observation. At this point it can either be used for support or supported by another statement. Let\'s keep reading.',
      'Statement 2: "Although many complain about government intervention in their lives, they tend not to re-elect inactive politicians" \u2014 This seems like a further development of statement 1. People say they want governments to leave them alone, but they don\'t like politicians who don\'t do anything. (In other words, politicians who actually do leave them alone don\'t get any support.) Statement 2 seems like a premise; maybe statement 1 is the conclusion or intermediate conclusion.',
      'Statement 3: "But a politician\'s activity consists largely in the passage of laws whose enforcement affects voters\' lives" \u2014 Stop and think. How does this tie in? In statement 2 we said voters don\'t vote for inactive politicians. This statement says what active politicians do \u2014 they interfere in voters\' lives. Inactive politicians don\'t get the votes, active ones do. So voters say they don\'t want interference but will vote for interfering politicians. Statements 2 and 3 are definitely premises.',
      'Statement 4: "Thus, voters often re-elect politicians whose behavior they resent" \u2014 It\'s the last statement and begins with "thus". It could signify the actual conclusion, but we must remember that often the test makers will present an intermediate conclusion this way. Here it IS the intermediate conclusion, while the first statement is in fact the conclusion.',
      'Simplified structure:\n\u2022 Premise 1: People want governments to leave them alone, but they don\'t vote for politicians who are inactive. (Assumption: It\'s the active politicians who get the votes)\n\u2022 Premise 2: Active politicians don\'t leave people alone.\n\u2022 Intermediate Conclusion: People end up voting for politicians that do things they don\'t like (interference).\n\u2022 Conclusion: What people say (leave me alone!) doesn\'t match what they do (vote for interfering politicians).',
    ],
    structuralMap: [
      { label: 'Conclusion', text: 'People\'s political behavior frequently does not match their rhetoric.' },
      { label: 'Premise 1', text: 'Although many complain about government intervention in their lives, they tend not to re-elect inactive politicians.' },
      { label: 'Premise 2', text: 'But a politician\'s activity consists largely in the passage of laws whose enforcement affects voters\' lives.' },
      { label: 'Intermediate Conclusion', text: 'Thus, voters often re-elect politicians whose behavior they resent.' },
    ],
    answerBreakdowns: [
      { letter: 'A', text: 'It describes a phenomenon for which the argument\'s conclusion is offered as an explanation', explanation: 'We have seen this kind of structure before. A phenomenon is presented, and a cause is provided. Why is John grumpy? Because he didn\'t have his morning coffee. The statement in question is not a phenomenon that the conclusion provides the cause for. If the argument read like this, then A would be correct: "Voters tend not to re-elect inactive politicians. This is because people forget about politicians who haven\'t done anything and people vote for those that have made a strong impression."', isCorrect: false },
      { letter: 'B', text: 'It is a premise offered in support of the conclusion that voters often re-elect politicians whose behavior they resent', explanation: 'It is indeed a premise, and it is supporting the (intermediate) conclusion that voters often re-elect politicians whose behavior they resent. On the LSAT, the word "conclusion" can refer to both the main conclusion and the intermediate conclusion. "Conclusion of the argument as a whole" means main conclusion. So while the wording should raise some eyebrows, it\'s not wrong.', isCorrect: true },
      { letter: 'C', text: 'It is offered as an example of how a politician\'s activity consists largely in the passage of laws whose enforcement interferes with voters\' lives', explanation: 'Active politicians interfering with voters\' lives is the message of the NEXT statement. This statement is about voters not re-electing inactive politicians \u2014 a different claim entirely.', isCorrect: false },
      { letter: 'D', text: 'It is a generalization based on the claim that people complain about government intervention in their lives', explanation: 'Generalizations and examples are related concepts. In an LSAT stimulus, a generalization is when you infer a rule based on specific facts/findings. If I saw 500 swans and they were all white, I can generalize by saying all swans are white. A "generalization based on the claim that people complain about government intervention" should look like: "All my neighbors complain about government interference, all my coworkers too: so people tend to complain when they perceive government intervention in their lives." That\'s not what happens here.', isCorrect: false },
      { letter: 'E', text: 'It is cited as evidence that people\'s behavior never matches their political beliefs', explanation: 'Two problems: (1) the conclusion is about behavior not matching rhetoric (what they say), not beliefs; (2) "never" is too strong \u2014 the stimulus says "frequently." Be careful with answer choices that are too strong. Degree-based errors are frequent in wrong answer choices.', isCorrect: false },
    ],
    takeaway: 'On the LSAT, "conclusion" can mean both main and intermediate conclusion. "Conclusion of the argument as a whole" specifically means the MAIN conclusion. When an answer choice says just "conclusion," it can legitimately refer to an intermediate conclusion.',
  },
  {
    id: 'PT70-S4-Q24',
    stimulus: 'Biologist: Scientists have discovered fossilized bacteria in rocks 3.5 billion years old. The fossils indicate that these bacteria were quite complex and so must have already had a long evolutionary history when fossilized 3.5 billion years ago. However, Earth is only 4.6 billion years old, so the first life on Earth must have appeared soon after the planet\'s formation, when conditions were extremely harsh. This suggests that life may be able to arise under many difficult conditions throughout the universe.',
    questionStem: 'Which one of the following most accurately describes the role played in the biologist\'s argument by the claim that fossilized bacteria discovered in rocks 3.5 billion years ago must have had a long evolutionary history?',
    options: [
      { letter: 'A', text: 'It is a claim for which no support is provided in the argument, and that is used to illustrate the conclusion of the argument as a whole' },
      { letter: 'B', text: 'It is a claim for which no support is provided in the argument, and that itself is used to support a claim that in turn lends support to the conclusion of the argument as a whole' },
      { letter: 'C', text: 'It is a claim for which some support is provided in the argument, and that itself is used to support another claim that in turn lends support to the conclusion of the argument as a whole' },
      { letter: 'D', text: 'It is a claim for which some support is provided in the argument, and that itself is not used to support any other claim in the argument' },
      { letter: 'E', text: 'It is a claim for which some support is provided in the argument, and that itself is used to support two distinct conclusions, neither of which is intended to provide support for the other' },
    ],
    correctAnswer: 'C',
    transitionNote: 'Notice how only the second half of the second statement is underlined. The second statement actually contains two pieces of information: "bacteria were complex" AND that "they must have had a long evolutionary history." The question is asking about the part regarding "long evolutionary history," it never mentioned the "complex" part. The lesson is to always focus on exactly what the question is asking about \u2014 never just automatically assume we are looking at the entire sentence.',
    walkthrough: [
      'Statement 1: "Scientists have discovered fossilized bacteria in rocks 3.5 billion years old." \u2014 This is a fact and most likely background information.',
      'Statement 2: "The fossils indicate that these bacteria were quite complex and so must have already had a long evolutionary history when fossilized 3.5 billion years ago." \u2014 Careful with this one \u2014 it may only be one sentence but there\'s a lot of information. The bacteria were complex, so they must have had a long evolutionary history. There is a mini-argument here! The author is assuming that complexity means the bacteria had a long time to develop. Even within this sentence, there is both a premise and an intermediate conclusion.\n\nPremise (bacteria were complex) + Assumption (more complex = more time to evolve) \u2192 Intermediate Conclusion (these bacteria had already been around for a long time when they fossilized 3.5 billion years ago)',
      'Statement 3: "However, Earth is only 4.6 billion years old, so the first life on Earth must have appeared soon after the planet\'s formation, when conditions were extremely harsh." \u2014 Statement 2 said bacteria had been around for a long time before 3.5 billion years ago. If Earth is only 4.6 billion years old, we can infer the bacteria appeared soon after Earth was formed. Statement 3 also contains new information: conditions were harsh when earth was just formed.',
      'The last statement, "life may be able to arise under many difficult conditions throughout the universe," is the conclusion. Because bacteria appeared under harsh conditions on earth, the author concludes that life can arise under harsh conditions in the universe.',
      'This argument is structurally quite complex. The statement we are analyzing \u2014 "bacteria must have had a long evolutionary history" \u2014 is right in the middle of the argument chain. It has support (bacteria were complex), which makes it an intermediate conclusion; but it is also supporting another intermediate conclusion down the road.',
    ],
    structuralMap: [
      { label: 'Background', text: 'Scientists have discovered fossilized bacteria in rocks 3.5 billion years old.' },
      { label: 'Premise (Support for IC)', text: 'The fossils indicate that these bacteria were quite complex...' },
      { label: 'Intermediate Conclusion 1', text: '...and so must have already had a long evolutionary history when fossilized 3.5 billion years ago.' },
      { label: 'Intermediate Conclusion 2', text: 'However, Earth is only 4.6 billion years old, so the first life on Earth must have appeared soon after the planet\'s formation, when conditions were extremely harsh.' },
      { label: 'Main Conclusion', text: 'This suggests that life may be able to arise under many difficult conditions throughout the universe.' },
    ],
    answerBreakdowns: [
      { letter: 'A', text: 'It is a claim for which no support is provided in the argument, and that is used to illustrate the conclusion of the argument as a whole', explanation: 'Does our statement have support in the argument? It\'s easily missed but it\'s still there: because the bacteria were complex, so they must have a long evolutionary history. The complexity of the bacteria is the support. Is it an illustration (example) of the main conclusion? No.', isCorrect: false },
      { letter: 'B', text: 'It is a claim for which no support is provided in the argument, and that itself is used to support a claim that in turn lends support to the conclusion of the argument as a whole', explanation: 'Same problem as A \u2014 there IS support for the claim (bacteria were complex). The rest of the answer has no problems with it, but that only makes it a partially correct answer. Partially correct = wrong on the LSAT.', isCorrect: false },
      { letter: 'C', text: 'It is a claim for which some support is provided in the argument, and that itself is used to support another claim that in turn lends support to the conclusion of the argument as a whole', explanation: 'Support is indeed provided (complexity of bacteria). The statement supports Intermediate Conclusion #2 (life appeared soon after formation), which further supports the main conclusion (life can arise under difficult conditions). This perfectly matches the argument chain.', isCorrect: true },
      { letter: 'D', text: 'It is a claim for which some support is provided in the argument, and that itself is not used to support any other claim in the argument', explanation: 'The only statement that is not being used to support anything else in an argument is the main conclusion. What D is referring to here is the main conclusion. This statement clearly supports another claim.', isCorrect: false },
      { letter: 'E', text: 'It is a claim for which some support is provided in the argument, and that itself is used to support two distinct conclusions, neither of which is intended to provide support for the other', explanation: 'This describes an intermediate conclusion supporting two separate main conclusions. The stimulus has a single chain of support, not two independent conclusions.', isCorrect: false },
    ],
    takeaway: 'Always focus on exactly what the question asks about. A single sentence can contain multiple pieces of information \u2014 a premise AND an intermediate conclusion within the same sentence. Read carefully.',
  },
  {
    id: 'PT70-S1-Q17',
    stimulus: 'Meteorologist: Heavy downpours are likely to become more frequent if Earth\'s atmosphere becomes significantly warmer. A warm atmosphere heats the oceans, leading to faster evaporation, and the resulting water vapor forms rain clouds more quickly. A warmer atmosphere also holds more moisture, resulting in larger clouds. In general, as water vapor in larger clouds condenses, heavier downpours are more likely to result.',
    questionStem: 'Which one of the following most accurately describes the role played in the meteorologist\'s argument by the claim that, in general, as water vapor in larger clouds condenses, heavier downpours are more likely to result?',
    options: [
      { letter: 'A', text: 'It is the only conclusion in the argument' },
      { letter: 'B', text: 'It is the conclusion of the argument as a whole but is not the only explicitly stated conclusion in the argument' },
      { letter: 'C', text: 'It is a statement that the argument is intended to support but is not the conclusion of the argument as a whole' },
      { letter: 'D', text: 'It is used to support the only conclusion in the argument' },
      { letter: 'E', text: 'It provides a causal explanation of the phenomenon described by the conclusion of the argument as a whole, but it is not intended to provide support for that conclusion' },
    ],
    correctAnswer: 'D',
    preTeaching: 'CAUSALITY VS. ARGUMENT STRUCTURE\n\nBefore we dive into this question, let\'s return to the topic of causality vs argument structure. It\'s a subject which confuses even the most advanced students.\n\nRemember: if there is a cause and effect relationship in a LR argument, don\'t automatically assume that the cause is the premise and the effect is the conclusion.\n\nEXAMPLE 1 \u2014 John & Netflix:\nJohn couldn\'t wake up on time for his morning class. John usually has trouble waking up in the morning when he stays up late watching Netflix. Therefore John probably has been binge watching Netflix again last night.\n\nCause/Effect: Watching Netflix (Cause) \u2192 Cannot wake up early (Effect)\nBut structurally:\n\u2022 Premise 1: John couldn\'t wake up early\n\u2022 Premise 2: John has trouble waking up early when he watches Netflix\n\u2022 Conclusion: John was probably watching Netflix last night\n\nThe cause is the CONCLUSION, not the premise!\n\nEXAMPLE 2 \u2014 Megan\'s Coffee (Causal Chain):\nBecause Megan missed her morning coffee she was not paying attention to her surroundings. As a result she fell down the stairs. So not getting your daily dose of caffeine can cause dangerous accidents.\n\nCausal chain: No Coffee (A) \u2192 Not Paying Attention (B) \u2192 Accident (C)\n\nBut structurally, how should we diagram this?\nThe conclusion is A \u2192 C. We have two pieces of information supporting it: A \u2192 B and B \u2192 C.\n\nIs there an intermediate conclusion? Remember that an intermediate conclusion is ALWAYS supported by a premise. Does A \u2192 B support in any way B \u2192 C? No. They are two independent causal relationships. Yes they form the same causal chain, but there is no supporting relationship between the two.\n\nStructurally:\n\u2022 Premise: A \u2192 B\n\u2022 Premise: B \u2192 C\n\u2022 Conclusion: A \u2192 C\n\nJust because there is a causal logic chain A \u2192 B \u2192 C doesn\'t mean that A is the premise, B the intermediate conclusion, and C the conclusion!\n\nEXAMPLE 3 \u2014 YLS Conditional:\nIf you went to Yale Law School, then you must have gotten a great LSAT score. Every high LSAT scorer is a proficient computer user. So all YLS students are proficient computer users.\n\nConditionally: YLS \u2192 Great LSAT \u2192 Computer Skills\nStructurally:\n\u2022 Premise: YLS \u2192 Great LSAT\n\u2022 Premise: Great LSAT \u2192 Computer Skills\n\u2022 Conclusion: YLS \u2192 Computer Skills\n\nIs "Great LSAT \u2192 Computer Skills" an intermediate conclusion? No. Because "YLS \u2192 Great LSAT" is not supporting "Great LSAT \u2192 Computer Skills." They are each independent premises that, when combined, lead to the conclusion.\n\nKEY TAKEAWAY:\nJust because a statement/idea/condition forms the middle part of a causal or conditional chain, that doesn\'t make it the intermediate conclusion. Always treat the structure of an argument (premise, intermediate conclusion, main conclusion) and the logical aspects of the argument (cause/effect, sufficient/necessary) as two distinct and separate issues!\n\nCause \u2192 Effect is NOT the same as Premise \u2192 Conclusion.\nSufficient \u2192 Necessary is NOT the same as Premise \u2192 Conclusion.',
    walkthrough: [
      'Statement 1: "Heavy downpours are likely to become more frequent if Earth\'s atmosphere becomes significantly warmer."\nWarmer atmosphere \u21d2 More frequent heavy downpours\nThis is the CONCLUSION (first sentence).',
      'Statement 2: "A warm atmosphere heats the oceans, leading to faster evaporation, and the resulting water vapor forms rain clouds more quickly."\nWarm atmosphere \u21d2 Hotter ocean \u21d2 Faster evaporation \u21d2 Faster rain cloud formation',
      'Statement 3: "A warmer atmosphere also holds more moisture, resulting in larger clouds."\nWarm atmosphere \u21d2 Larger clouds',
      'Statement 4: "In general, as water vapor in larger clouds condenses, heavier downpours are more likely to result."\nLarger clouds \u21d2 More frequent heavy downpours',
      'Reorganized structurally:\n\u2022 Premise 1: Warm atmosphere \u21d2 Faster rain cloud formation\n\u2022 Premise 2: Warm atmosphere \u21d2 Larger clouds\n\u2022 Premise 3: Larger clouds \u21d2 More frequent heavy downpours\n\u2022 Conclusion: Warm atmosphere \u21d2 More frequent heavy downpours\n\nThe statement we are analyzing is the last statement (Premise 3). There is NO intermediate conclusion \u2014 the three premises independently support the conclusion.',
    ],
    structuralMap: [
      { label: 'Conclusion', text: 'Heavy downpours are likely to become more frequent if Earth\'s atmosphere becomes significantly warmer. (Warmer atmosphere \u2192 More frequent heavy downpours)' },
      { label: 'Premise 1', text: 'A warm atmosphere heats the oceans, leading to faster evaporation, and the resulting water vapor forms rain clouds more quickly. (Warm atmosphere \u2192 Faster rain cloud formation)' },
      { label: 'Premise 2', text: 'A warmer atmosphere also holds more moisture, resulting in larger clouds. (Warm atmosphere \u2192 Larger clouds)' },
      { label: 'Premise 3', text: 'In general, as water vapor in larger clouds condenses, heavier downpours are more likely to result. (Larger clouds \u2192 More frequent heavy downpours)' },
    ],
    answerBreakdowns: [
      { letter: 'A', text: 'It is the only conclusion in the argument', explanation: 'The statement we are analyzing is the last statement and is a premise (Premise 3: Larger clouds \u2192 More frequent heavy downpours). It is NOT the conclusion. The conclusion is the first statement.', isCorrect: false },
      { letter: 'B', text: 'It is the conclusion of the argument as a whole but is not the only explicitly stated conclusion in the argument', explanation: 'Same problem \u2014 this is not the conclusion. The conclusion is the first statement.', isCorrect: false },
      { letter: 'C', text: 'It is a statement that the argument is intended to support but is not the conclusion of the argument as a whole', explanation: 'This describes an intermediate conclusion. But statement 4 is not supported by any other statement in the argument \u2014 it is a standalone premise. No other statement provides evidence for it.', isCorrect: false },
      { letter: 'D', text: 'It is used to support the only conclusion in the argument', explanation: 'Correct. The statement is Premise 3, which supports the only conclusion (statement 1). There is no intermediate conclusion \u2014 the three premises independently support the conclusion.', isCorrect: true },
      { letter: 'E', text: 'It provides a causal explanation of the phenomenon described by the conclusion of the argument as a whole, but it is not intended to provide support for that conclusion', explanation: 'The statement IS intended to provide support for the conclusion. The causal chain (warm \u2192 larger clouds \u2192 heavier downpours) serves as evidence for the conclusion. Don\'t confuse the causal logic with the argument structure!', isCorrect: false },
    ],
    causalTrapWarning: 'CAUSAL TRAP WARNING: Just because there is a causal chain (A \u2192 B \u2192 C) doesn\'t mean A is the premise, B the intermediate conclusion, and C the conclusion!\n\nConsider Megan\'s Coffee: "Because Megan missed her morning coffee she was not paying attention to her surroundings. As a result she fell down the stairs. So not getting your daily dose of caffeine can cause dangerous accidents."\n\nCausal chain: No Coffee (A) \u2192 Not Paying Attention (B) \u2192 Accident (C)\nBut structurally: Premise: A\u2192B, Premise: B\u2192C, Conclusion: A\u2192C\n\nDoes A\u2192B support B\u2192C? No. They are two independent causal relationships that happen to form the same chain. Always treat the structure of an argument (premise/conclusion) and the logical aspects (cause/effect, sufficient/necessary) as two distinct and separate issues!',
    takeaway: 'Having a clear understanding of the stimulus\' structure is crucial to tackling Role questions. We must also constantly practice our ability to decipher what each answer choice is saying and matching that up with the stimulus.',
  },
  {
    id: 'PT87-S3-Q8',
    stimulus: 'Astronomer: Conditions in our solar system have probably favored the emergence of life more than conditions in most other solar systems of similar age. Any conceivable form of life depends on the presence of adequate amounts of chemical elements heavier than hydrogen and helium, and our sun has an unusually high abundance of these heavier elements for its age.',
    questionStem: 'Which one of the following most accurately describes the role played in the astronomer\'s argument by the claim that any conceivable form of life depends on chemical elements heavier than hydrogen and helium?',
    options: [
      { letter: 'A', text: 'It is a statement for which no evidence is provided and that is part of the evidence offered for the argument\'s only conclusion' },
      { letter: 'B', text: 'It is a statement for which no evidence is provided and that is offered as support for another statement that in turn is offered as support for the conclusion of the argument as a whole' },
      { letter: 'C', text: 'It is a statement for which some evidence is provided and that itself is offered as support for the conclusion of the argument as a whole' },
      { letter: 'D', text: 'It is the conclusion of the argument as a whole and is supported by another statement for which support is offered' },
      { letter: 'E', text: 'It is one of two conclusions in the argument, neither of which is offered as support for the other' },
    ],
    correctAnswer: 'A',
    difficultTrait: {
      number: 2,
      title: 'Watch for Abstract Terms in Answer Choices',
      text: 'Be extra careful of vague/abstract terms in answer choices. Try to match them up with what actually happened in the stimulus.',
    },
    walkthrough: [
      'The first statement has the word "probably," indicating that it\'s an opinion of the author. The author believes that our solar system is better suited to life than other solar systems. Let\'s see why.',
      'Statement 2 says that life needs a lot of chemicals heavier than hydrogen and helium, while Statement 3 says that our solar system has plenty of both. Statements 2 and 3 are INDEPENDENT premises supporting statement 1, the conclusion. There is no intermediate conclusion here.',
      'Structure:\n\u2022 Conclusion: Our solar system probably favors life more than others\n\u2022 Premise 1: Life needs heavy chemical elements\n\u2022 Premise 2: Our sun has unusually high abundance of heavy elements\n\nThe two premises independently support the conclusion. Neither supports the other.',
    ],
    structuralMap: [
      { label: 'Conclusion', text: 'Conditions in our solar system have probably favored the emergence of life more than conditions in most other solar systems of similar age.' },
      { label: 'Premise 1', text: 'Any conceivable form of life depends on the presence of adequate amounts of chemical elements heavier than hydrogen and helium.' },
      { label: 'Premise 2', text: 'Our sun has an unusually high abundance of these heavier elements for its age.' },
    ],
    answerBreakdowns: [
      { letter: 'A', text: 'It is a statement for which no evidence is provided and that is part of the evidence offered for the argument\'s only conclusion', explanation: 'Answer choice A says the underlined statement is a premise (no evidence provided), and the argument contains no intermediate conclusion (argument\'s only conclusion). Is it the premise that we are examining? Yes. Does the argument contain an intermediate conclusion? No. This matches perfectly.', isCorrect: true },
      { letter: 'B', text: 'It is a statement for which no evidence is provided and that is offered as support for another statement that in turn is offered as support for the conclusion of the argument as a whole', explanation: 'Answer choice B also calls the underlined statement a premise, but according to this answer choice, there is an intermediate conclusion in the stimulus. Do we have an intermediate conclusion present? No. Earth having a lot of heavy elements does not support the fact that we need these elements to support life, nor does life needing heavy elements support the fact that earth has a lot of them. They are independent.', isCorrect: false },
      { letter: 'C', text: 'It is a statement for which some evidence is provided and that itself is offered as support for the conclusion of the argument as a whole', explanation: 'C is essentially talking about an intermediate conclusion ("some evidence is provided" for it). Again, there is no intermediate conclusion in this stimulus. This is a standalone premise.', isCorrect: false },
      { letter: 'D', text: 'It is the conclusion of the argument as a whole and is supported by another statement for which support is offered', explanation: 'Answer choice D is saying that the underlined statement is the main conclusion (it isn\'t \u2014 that\'s statement 1), and that there is an intermediate conclusion in this stimulus/argument (there isn\'t).', isCorrect: false },
      { letter: 'E', text: 'It is one of two conclusions in the argument, neither of which is offered as support for the other', explanation: 'Answer choice E is describing a scenario with two conclusions but no intermediate conclusion. Example: "John has been admitted to YLS. John has a high GPA and a high LSAT score." Two conclusions, neither supporting the other. That\'s not what we have \u2014 there\'s only one conclusion here.', isCorrect: false },
    ],
    takeaway: 'In the hardest questions, sometimes it\'s not enough to simply identify the premise, intermediate conclusion and main conclusion. We must also read the answer choice word for word and refer back to the stimulus to prove or reject the answer based on the evidence available.',
  },
  {
    id: 'PT79-S1-Q22',
    stimulus: 'Consumer advocate: Economists reason that price gouging \u2014 increasing the price of goods when no alternative seller is available \u2014 is efficient because it allocates goods to people whose willingness to pay more shows that they really need these goods. But willingness to pay is not proportional to need. In the real world, some people simply cannot pay as much as others. As a result, a price increase will allocate goods to people with the most money, not to those with the most need.',
    questionStem: 'Which one of the following most accurately describes the role played in the consumer advocate\'s argument by the claim that willingness to pay is not proportional to need?',
    options: [
      { letter: 'A', text: 'It disputes one explanation in order to make way for an alternative explanation' },
      { letter: 'B', text: 'It is the overall conclusion of the argument' },
      { letter: 'C', text: 'It is a component of the reasoning disputed in the argument' },
      { letter: 'D', text: 'It is a general principle whose validity the argument questions' },
      { letter: 'E', text: 'It denies a claim that the argument takes to be assumed in the reasoning that it rejects' },
    ],
    correctAnswer: 'E',
    walkthrough: [
      'Statement 1: "Economists reason that price gouging \u2014 increasing the price of goods when no alternative seller is available \u2014 is efficient because it allocates goods to people whose willingness to pay more shows that they really need these goods." \u2014 This is an opposing argument, or what the consumer advocate is arguing against. The economists\' argument: if you are willing to pay more for a good, you must need it more. So price gouging is efficient.',
      'Statement 2: "But willingness to pay is not proportional to need" \u2014 This is the consumer advocate\'s opinion. They are attacking the reasoning behind the economists\' premise.',
      'Statement 3: "In the real world, some people simply cannot pay as much as others" \u2014 On a first glance, how this ties in is a little unclear. Whenever I read a statement that seems disconnected, my first reaction is "so what?" If some people cannot pay as much as others, then the person needing something the most (for example, an urgent medical treatment) may not necessarily be able to offer the highest price for it. So statement 3 is supporting statement 2.',
      'Statement 4: "As a result, a price increase will allocate goods to people with the most money, not to those with the most need." \u2014 This is in direct opposition to the economists\' reasoning, and therefore the consumer advocate\'s conclusion.',
      'Diagram:\n\nEconomists: [If someone is willing to pay a higher price, that means they need it more] \u2192 [Price Gouging is Efficient]\n\nConsumer Advocate: [Some people just don\'t have money] \u2192 [Paying more doesn\'t mean you need it more] \u2192 [Price gouging benefits the rich, not those who need it most]\n\nStructurally, statement 2 ("willingness to pay is not proportional to need") is the consumer advocate\'s intermediate conclusion in their response to the economists. It\'s an attack on the economists\' premise.',
    ],
    structuralMap: [
      { label: 'Opposing Argument (Economists)', text: 'Price gouging is efficient because willingness to pay more shows real need. [Assumption: willingness to pay IS proportional to need]' },
      { label: "Consumer Advocate's Attack (Intermediate Conclusion)", text: 'But willingness to pay is not proportional to need.' },
      { label: 'Premise (Support for IC)', text: 'In the real world, some people simply cannot pay as much as others.' },
      { label: 'Main Conclusion', text: 'As a result, a price increase will allocate goods to people with the most money, not to those with the most need.' },
    ],
    answerBreakdowns: [
      { letter: 'A', text: 'It disputes one explanation in order to make way for an alternative explanation', explanation: 'Tricky! Remember what the word "explanation" means on the LSAT? It has a very precise definition and means "causation." So what this answer choice is saying is that the author is disputing one cause in order to make way for another cause. If this is correct, the stimulus would look like: "John: A is caused by B. David: No, A is not caused by B, it\'s caused by C." Does this happen in our stimulus? No. If the consumer advocate had said that price gouging is efficient NOT because it allocates goods to the willing, BUT because it allows companies to earn more profits, then this could be correct.\n\nThis is the most commonly selected wrong answer. The takeaway: we must read answer choices word for word. The word "explanation" should be a red flag.', isCorrect: false },
      { letter: 'B', text: 'It is the overall conclusion of the argument', explanation: 'The overall conclusion is the last statement of the stimulus: price increases allocate goods to the rich, not the needy.', isCorrect: false },
      { letter: 'C', text: 'It is a component of the reasoning disputed in the argument', explanation: 'What the consumer advocate disputes is the economists\' reasoning. The statement we are concerned with forms a part of the consumer advocate\'s OWN reasoning, not a component OF the economists\' reasoning.', isCorrect: false },
      { letter: 'D', text: 'It is a general principle whose validity the argument questions', explanation: 'This statement is a part of the consumer advocate\'s argument. Its validity is NOT questioned \u2014 the consumer advocate is asserting it.', isCorrect: false },
      { letter: 'E', text: 'It denies a claim that the argument takes to be assumed in the reasoning that it rejects', explanation: 'Many students eliminate this answer simply because they had no idea what it\'s saying or failed to think on a deeper level.\n\nAnswer E is suggesting there is an assumption in the economists\' reasoning (the "reasoning that it rejects"), and that statement 2 ("willingness to pay is not proportional to need") is denying that assumption.\n\nDoes the economists\' reasoning contain an assumption? Remember what the economists\' argument was: if you are willing to pay more, it means you need it more, so price gouging is efficient. So the economists do believe that willingness to pay IS proportional to need \u2014 a direct contradiction of statement 2.\n\nE is the correct answer.', isCorrect: true },
    ],
    takeaway: 'When an answer choice is suspiciously vague and abstract, don\'t eliminate it just because you don\'t understand it. Break it up into pieces and match each piece with information from the stimulus. The "so what?" technique is also useful: when a statement seems disconnected, ask yourself what it implies.',
  },
  {
    id: 'PT59-S2-Q7',
    stimulus: 'Columnist: It has been noted that attending a live musical performance is a richer experience than listening to recorded music. Some say that this is merely because we do not see the performers when we listen to recorded music. However, there must be some other reason, for there is relatively little difference between listening to someone read a story over the radio and listening to someone in the same room read a story.',
    questionStem: 'Which one of the following most accurately expresses the role played in the argument by the observation that attending a live musical performance is a richer experience than is listening to recorded music?',
    options: [
      { letter: 'A', text: 'It is what the columnist\'s argument purports to show' },
      { letter: 'B', text: 'It is the reason given for the claim that the columnist\'s argument is attempting to undermine' },
      { letter: 'C', text: 'It is what the columnist\'s argument purports to explain' },
      { letter: 'D', text: 'It is what the columnist\'s argument purports to refute' },
      { letter: 'E', text: 'It is what the position that the columnist tries to undermine is purported to explain' },
    ],
    correctAnswer: 'E',
    difficultTrait: {
      number: 3,
      title: 'Brutally Abstract Stimuli',
      text: 'Role questions are famous for brutally abstract stimuli/arguments. When faced with an abstract argument in the stimulus, don\'t be afraid to slow down, summarize each statement, and rearrange the information structurally.',
    },
    transitionNote: 'After finding the structure of the argument, put your primary focus on the answer choices. For each answer choice, ask yourself, "does this happen in the stimulus? If so, where?"',
    walkthrough: [
      'Statement 1: "It has been noted that attending a live musical performance is a richer experience than listening to recorded music." \u2014 An observation the columnist makes ("it has been noted"). This is not a part of the author\'s argument; it\'s the phenomenon being discussed.',
      'Statement 2: "Some say that this is merely because we do not see the performers when we listen to recorded music." \u2014 This presents one explanation (cause) for the observation made above. This is the opposing viewpoint.',
      'Statement 3: "However, there must be some other reason, for there is relatively little difference between listening to someone read a story over the radio and listening to someone in the same room read a story." \u2014 This is the columnist\'s conclusion (there must be some OTHER reason) plus the support for it (the story comparison).',
      'Simplified structure:\n\u2022 Statement 1: There is a phenomenon that has been noted (X = live music is richer)\n\u2022 Statement 2: Some believe X is caused by Y (Y = not seeing performers)\n\u2022 Statement 3: X cannot be caused by Y (conclusion), because... (premise)\n\nThe first statement is a scenario/phenomenon. It\'s not part of the author\'s argument. The author\'s argument only rejects the cause offered by others, without providing an alternative cause of their own.',
      'Compare with: "John has lung cancer. Smoking causes lung cancer. Therefore John must be a smoker."\n\nSimilarities: both arguments start with a phenomenon and attempt to find a cause.\nDifferences: In John\'s case, the author provides a cause. In our stimulus, the author ONLY rejects someone else\'s cause without providing their own.',
    ],
    structuralMap: [
      { label: 'Phenomenon / Observation', text: 'Attending a live musical performance is a richer experience than listening to recorded music.' },
      { label: 'Opposing View (Cause)', text: 'Some say this is merely because we do not see the performers when we listen to recorded music.' },
      { label: "Author's Conclusion", text: 'However, there must be some other reason...' },
      { label: 'Premise (Support)', text: '...for there is relatively little difference between listening to someone read a story over the radio and listening to someone in the same room read a story.' },
    ],
    answerBreakdowns: [
      { letter: 'A', text: 'It is what the columnist\'s argument purports to show', explanation: 'Answer choice A is referring to the main conclusion. We know that in our stimulus, statement 1 is a phenomenon for which we are looking for the cause. It\'s not the main conclusion.', isCorrect: false },
      { letter: 'B', text: 'It is the reason given for the claim that the columnist\'s argument is attempting to undermine', explanation: 'This answer choice reverses the cause-effect relationship. In the stimulus: not seeing performers (cause) \u2192 live music is a richer experience (effect). According to B, statement 1 is the REASON for the view attacked by the columnist. Fully expanded, B says: "Because attending a live musical performance is a richer experience, we do not see the performers when we listen to recorded music." That\'s backwards.', isCorrect: false },
      { letter: 'C', text: 'It is what the columnist\'s argument purports to explain', explanation: 'This is the most commonly selected wrong answer. Read the keywords: "explain" = "provide a cause for." Does the author explain (offer a cause) in their argument? Why is attending a live performance a richer experience? No \u2014 the author rejects another cause but doesn\'t offer any new alternatives. All correct answers will NEED to be matched with information in the stimulus.', isCorrect: false },
      { letter: 'D', text: 'It is what the columnist\'s argument purports to refute', explanation: 'Does the author reject the observation that "attending a live musical performance is a richer experience"? No. The author refutes an explanation for why this is the case, but accepts the phenomenon itself.', isCorrect: false },
      { letter: 'E', text: 'It is what the position that the columnist tries to undermine is purported to explain', explanation: 'Two words: keyword extraction. When an answer choice is suspiciously vague, break it up into pieces:\n\n"Position that the columnist tries to undermine" = the claim that we don\'t see performers when listening to recorded music (i.e., the opposing view\'s cause)\n\nWhat is this position purporting to explain? In other words, this position is a cause for what effect? The effect is the observation that "attending a live musical performance is a richer experience." Bingo.', isCorrect: true },
    ],
    takeaway: 'When an answer choice is suspiciously abstract, use keyword extraction: break it into pieces and match each piece with information from the stimulus. Also, be precise about whether the author explains (provides a cause) vs. merely rejects someone else\'s cause.',
  },
  {
    id: 'PT51-S3-Q23',
    stimulus: 'Ethicist: It would be a mistake to say that just because someone is not inclined to do otherwise, she or he does not deserve to be praised for doing what is right. For although we do consider people especially virtuous if they successfully resist a desire to do what is wrong, they are certainly no less virtuous if they have succeeded in extinguishing all such desires.',
    questionStem: 'The assertion that people are considered especially virtuous if they successfully resist a desire to do what is wrong plays which one of the following roles in the ethicist\'s argument?',
    options: [
      { letter: 'A', text: 'It is a claim for which the argument attempts to provide justification' },
      { letter: 'B', text: 'It makes an observation that, according to the argument, is insufficient to justify the claim that the argument concludes is false' },
      { letter: 'C', text: 'It is a claim, acceptance of which, the argument contends, is a primary obstacle to some people having an adequate conception of virtue' },
      { letter: 'D', text: 'It is, according to the argument, a commonly held opinion that is nevertheless false' },
      { letter: 'E', text: 'It reports an observation that, according to the argument, serves as evidence for the truth of its conclusion' },
    ],
    correctAnswer: 'E',
    difficultTrait: {
      number: 3,
      title: 'Brutally Abstract Stimuli',
      text: 'Role questions are famous for brutally abstract stimuli/arguments. When faced with an abstract argument, don\'t be afraid to slow down, summarize each statement, and rearrange the information structurally.',
    },
    walkthrough: [
      'This is one of the most abstract stimuli you will encounter. Let\'s break it down carefully.',
      'The ethicist\'s conclusion: "It would be a mistake to say that just because someone is not inclined to do otherwise, she or he does not deserve to be praised for doing what is right." In other words, people who naturally do the right thing (without being tempted to do wrong) STILL deserve praise.',
      'Support: "Although we do consider people especially virtuous if they successfully resist a desire to do what is wrong" \u2014 This is an observation that the ethicist accepts as true. People who resist temptation are considered especially virtuous.',
      '"They are certainly no less virtuous if they have succeeded in extinguishing all such desires" \u2014 The ethicist argues that those who have eliminated the desire to do wrong entirely are equally (or more) virtuous.',
      'The statement in question \u2014 that people are considered especially virtuous if they resist temptation \u2014 is presented as an accepted observation. The ethicist uses it as a starting point to build the argument. It serves as evidence: if resisting temptation makes you especially virtuous, then having no temptation at all certainly doesn\'t make you less virtuous.',
    ],
    structuralMap: [
      { label: 'Main Conclusion', text: 'It would be a mistake to say that just because someone is not inclined to do otherwise, she or he does not deserve to be praised for doing what is right.' },
      { label: 'Premise', text: 'Although we do consider people especially virtuous if they successfully resist a desire to do what is wrong, they are certainly no less virtuous if they have succeeded in extinguishing all such desires.' },
    ],
    answerBreakdowns: [
      { letter: 'A', text: 'It is a claim for which the argument attempts to provide justification', explanation: 'The argument does not attempt to justify why people who resist temptation are considered especially virtuous. It takes this observation as a given and builds upon it.', isCorrect: false },
      { letter: 'B', text: 'It makes an observation that, according to the argument, is insufficient to justify the claim that the argument concludes is false', explanation: 'The argument doesn\'t conclude that any claim is false in the way this answer describes. The ethicist is arguing against a potential mistake in reasoning, not declaring an observation insufficient.', isCorrect: false },
      { letter: 'C', text: 'It is a claim, acceptance of which, the argument contends, is a primary obstacle to some people having an adequate conception of virtue', explanation: 'The ethicist doesn\'t argue that accepting this observation is an obstacle. Rather, the ethicist accepts this observation and builds on it.', isCorrect: false },
      { letter: 'D', text: 'It is, according to the argument, a commonly held opinion that is nevertheless false', explanation: 'The ethicist does NOT say this observation is false. The ethicist accepts that people ARE considered especially virtuous if they resist temptation. The argument is about what follows from this observation.', isCorrect: false },
      { letter: 'E', text: 'It reports an observation that, according to the argument, serves as evidence for the truth of its conclusion', explanation: 'Correct. The observation (people who resist temptation are considered especially virtuous) is accepted as true and used as evidence to support the conclusion that people who have no temptation at all also deserve praise for doing right.', isCorrect: true },
    ],
    takeaway: 'When the stimulus is brutally abstract, slow down and translate each piece into plain language before looking at the answer choices. The ethicist uses an accepted observation as a stepping stone to make a broader point about virtue.',
  },
];
